(define (hearth:render identity organism)
  (monolith:start-offline)
  (monolith:realloc 8 10 49)
  (monolith:janet-init)
  (monolith:janet-eval (string-append "(import "identity")"))
  (monolith:gfx-fb-init)
  (monolith:gfx-setsize 192 256)
  (monolith:h264-begin (string-append identity ".h264") 60)
  (organism)
  (wavout zz (string-append identity ".wav"))
  (out zz)
  (monolith:janet-eval
   (string-append "("identity"/render-file)"))
  (monolith:h264-end))
