cd xuapanaos; sh render.sh; cd ..
cd shqfamauzk; sh render.sh; cd ..
cd naoyuguozk; sh render.sh; cd ..
cd xaothuthizk; sh render.sh; cd ..
cd xodayjao; sh render.sh; cd ..
cd fogozue; sh render.sh; cd ..
cd magopau; sh render.sh; cd ..
cd siigolue; sh render.sh; cd ..
cd taogoryxs; sh render.sh; cd ..
