(define knobkit-name "knobkit")
(define (knobkit-create) (monolith:knobs-new knobkit-name))
(define (knobkit-select)
  (monolith:page-select knobkit-name))
(define (knobkit-param p min max)
  (let* ((vals (car (cdr p)))
         (lane (car p))
         (x (car vals))
         (y (car (cdr vals))))
    (scale (knobsval lane x y knobkit-name) min max)))
(define (knobkit-sparam p min max smooth)
  (port (knobkit-param p min max) smooth))
